import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Hero from "../../components/hero";
import Blog from "../../components/publikasi";
import Team from "../../components/team";

const inter = Inter({ subsets: ["latin"] });

export default function Home(data) {
  const hero = data.attributes;

  return (
    <>
      <Head>
        <title>IKKAN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/ikkan.png" />
      </Head>
      <main>
        <Hero hero={hero} />
        <Blog />
        <Team />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const qs = require("qs");
  const query = qs.stringify(
    {
      populate: "*",
    },
    {
      encodeValuesOnly: true,
    }
  );
  const res = await fetch(
    process.env.NEXT_PUBLIC_HOST + "/api/hero-component?" + query,
    {
      headers: {
        Authorization: `Bearer ${process.env.NEXT_PUBLIC_TOKEN}`,
      },
    }
  );
  const { data } = await res.json();
  return {
    props: data,
  };
}
